### ISSUE TITLE
Does not work with python 3.x

### ISSUE THREAD

**Issue by grayaii** [NateFerrero/quicklock#2]
Using Python 3.4.3, this module does not work:

``` python

>>> from quicklock import singleton
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/alexgray/.virtualenvs/skippy/lib/python3.4/site-packages/quicklock/__init__.py", line 1, in <module>
    from quicklock import singleton
ImportError: cannot import name 'singleton'

```

It works fine with python version < 3

**Comment by dachshund-digital** [comment]
Bump can we get this fixed?
